Un sistema lineal de n ecuaciones en n variables reales toma la forma:

$a_{11}x_1 + a_{12}x_2 + a_{13}x_3 + ... + a_{1n}x_n = f_1$

$a_{21}x_1 + a_{22}x_2 + a_{23}x_3 + ... + a_{2n}x_n = f_2$
.

.

.

$a_{n1}x_1 + a_{n2}x_2 + a_{n3}x_3 + ... + a_{nn}x_n = f_n$

$a_{ij},x_i,f_i \in R,C$

Ahora bien tenemos que:

$a_{ij}^{k+1}$ = $a_{ij}^k$ - $m_{ik}a_{kj}^k$ 

$m_{ik} = \frac{a_{ik}^k}{a_{kk}^k}$

$f_i^{k+1}$ = $f_i^k - m_kf_k^k$

In [1]:
import numpy as np
import sympy as sy
from sympy import *
from sympy.abc import x
import matplotlib.pyplot as plt

In [2]:
A = np.array([[1,2,3],[4,5,6],[7,8,10]])

print(A)
F = np.array([3,4,5])

print(F)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
[3 4 5]


In [3]:
def al(A,F):
    U = np.copy(A)
    G = np.copy(F)
    n = F.size
    for j in range(n-1):
        for i in range(j+1,n):
            M =U[i,j]/U[j,j]
            U[i,j:] = U[i,j:] - (M*U[j,j:])
            G[i]=G[i] - (M*G[j])
    return U,G

            


In [4]:
U=al(A,F)[0]
print(U)
G=al(A,F)[1]
print(G)

[[ 1  2  3]
 [ 0 -3 -6]
 [ 0  0  1]]
[ 3 -8  0]


In [5]:
def sol(U,G):
    n = G.size
    x = np.zeros(n)
    aux = 0
    for i in reversed(range(n)):
        if i == n-1:
            x[i] = (G[i])/(U[i,i])
            continue
        else:
            for j in range (i+1,n):
                aux += U[i,j]*x[j]
            x[i] = (G[i]/U[i,i]) - (1/U[i,i])*aux
            aux = 0
    return x

In [6]:
sol(U,G)

array([-2.33333333,  2.66666667,  0.        ])

2
1
0


[None, None, None]