Métodos de factorización directa:



In [1]:
import numpy as np
import sympy as sy
from sympy import *
from sympy.abc import x
import matplotlib.pyplot as plt

In [2]:
a = 3
A = np.array([[1,3,3],[4,5,6],[7,8,10]])
L = np.identity(3)
U = np.zeros((3,3))
display(L)
display(U)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
for i in range(a):
    for j in range(i,a):
        u=0
        for k in range(i):
            u += L[i,k]*U[k,j]
        U[i,j] = A[i,j]-u
    for j in range(i+1,a):
        l=0
        for k in range(i):
            l += L[j,k]*U[k,i]
        L[j,i] = (A[j,i]-l)/U[i,i]
        u=0            

In [4]:
display(U)

array([[ 1.        ,  3.        ,  3.        ],
       [ 0.        , -7.        , -6.        ],
       [ 0.        ,  0.        ,  0.14285714]])

In [5]:
display(L)

array([[1.        , 0.        , 0.        ],
       [4.        , 1.        , 0.        ],
       [7.        , 1.85714286, 1.        ]])

In [6]:
c=np.zeros((3,3))
c=np.matmul(L,U)
display(c)

array([[ 1.,  3.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8., 10.]])