Un sistema lineal de n ecuaciones en n variables reales toma la forma:

$a_{11}x_1 + a_{12}x_2 + a_{13}x_3 + ... + a_{1n}x_n = f_1$

$a_{21}x_1 + a_{22}x_2 + a_{23}x_3 + ... + a_{2n}x_n = f_2$
.

.

.

$a_{n1}x_1 + a_{n2}x_2 + a_{n3}x_3 + ... + a_{nn}x_n = f_n$

$a_{ij},x_i,f_i \in R,C$

Ahora bien tenemos que:

$a_{ij}^{k+1}$ = $a_{ij}^k$ - $m_{ik}a_{kj}^k$ 

$m_{ik} = \frac{a_{ik}^k}{a_{kk}^k}$

$f_i^{k+1}$ = $f_i^k - m_kf_k^k$

In [1]:
import numpy as np
import sympy as sy
from sympy import *
from sympy.abc import x
import matplotlib.pyplot as plt

In [7]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(A)
F = np.array([3,4,5])

print(F)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 4 5]


In [14]:
def al(k,A,F):
    for i in range(k):
        for j in range(0,2):
            U[i,j] = A[i,j] - ((A[i,k])/(A[k,k]))*A[k,j]
    G[k]=F[k] - ((A[i,k])/(A[k,k]))*F[k]
    k+=1
    if k==2:
        x = G[k]/U[k,k]
        return x
    else:
        return al(k,U,G,U,G)

In [15]:
U = np.array([[1,2,3],[0,0,0],[0,0,0]])
G = np.array([0,0,])
k=1
al(k,A,F)

IndexError: index 0 is out of bounds for axis 1 with size 0