Métodos de factorización directa:



In [1]:
import numpy as np
import sympy as sy
from sympy import *
from sympy.abc import x
import matplotlib.pyplot as plt

In [95]:
a = 3
A = np.array([[1,3,3],[4,5,6],[7,8,10]])
L = np.identity(3)
U = np.zeros((3,3))
display(L)
display(U)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [96]:
for i in range(a):
    for j in range(i,a):
        u=0
        for k in range(i):
            u += L[i,k]*U[k,j]
        U[i,j] = A[i,j]-u
    for j in range(i+1,a):
        l=0
        for k in range(i):
            l += L[j,k]*U[k,i]
        L[j,i] = (A[i,j]-l)/U[i,i]
        u=0            

In [97]:
display(U)

array([[ 1.  ,  3.  ,  3.  ],
       [ 0.  , -4.  , -3.  ],
       [ 0.  ,  0.  ,  3.25]])

In [98]:
display(L)

array([[1.  , 0.  , 0.  ],
       [3.  , 1.  , 0.  ],
       [3.  , 0.75, 1.  ]])

In [105]:
c=np.zeros((3,3))
c=np.matmul(L,U)
display(c)

array([[ 1.,  3.,  3.],
       [ 3.,  5.,  6.],
       [ 3.,  6., 10.]])

array([[2.        , 3.        , 3.        ],
       [3.        , 2.        , 2.14285714],
       [3.        , 0.75      , 2.        ]])

In [80]:
def luDecomposition(A, n): 

    L = np.zeros((n, n))  
    U = np.zeros((n, n))

    print(L)

    for k in range (n):
        for i in range(k,n):
            sum1=0
            for p in range (k):
                sum1+=L[i][p]*U[p][k]
            L[i][k]=(A[i][k]-sum1)

        for i in range(k+1,n):
            if L[k][k] == 0:
                exit('Debe usar el pivoteo parcial')
            sum2=0
            for p in range(k):
                sum2+=L[k][p]*U[p][i]
            U[k][i]=(A[k][i]-sum2)/L[k][k]

    U = U + np.eye(n, dtype=float)

    return L,U

[[ 1.    3.    3.  ]
 [ 0.   -4.    1.2 ]
 [ 0.    0.    3.25]]


[[  1.           3.           3.        ]
 [  4.           5.           2.14285714]
 [  7.           8.         -11.        ]]
